name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Maven Verify
      run: mvn -B clean verify

    - name: Test Coverage
      run: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
